In [1]:
import numpy as np

In [2]:
l = np.array([5,-2, 3, 2])

In [3]:
ranks = np.argsort(l) 

In [4]:
np.array(l)[ranks]

array([-2,  2,  3,  5])

In [5]:
l, ranks + 1

(array([ 5, -2,  3,  2]), array([2, 4, 3, 1]))

In [6]:
4, 1, 3, 2

(4, 1, 3, 2)

In [7]:
np.argsort(ranks) + 1

array([4, 1, 3, 2])

In [16]:
X = np.random.normal(size = 100)
X = np.array([5,2,3,4,1])
ranks = np.argsort(X)
all(np.argsort(np.argsort(np.argsort(X))) == np.argsort(X))

True

In [25]:
X

array([5, 2, 3, 4, 1])

In [26]:
X[ranks]

array([1, 2, 3, 4, 5])

In [24]:
np.argsort(ranks)

array([4, 1, 2, 3, 0])